def _BUILD_NUMBER
_BUILD_NUMBER=env.BUILD_NUMBER

pipeline {
  agent any
  
  environment {
    DEMO= "beta"
  }

  stages {     
    stage('step 1') {
      steps {
        echo "this is the build $BUILD_NUMBER"
        sh '''
          echo "using a multi-lien shell step"
          chmod +x test.sh
          ./test.sh
        '''
      }
    }
    stage('deploy') {
      input {
        message 'Deploy?'
        ok 'Do it!'
        parameters {
          string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD')
        }
      }
      steps {
        echo "deploy release ${TARGET_ENVIRONMENT}"
      }
    }
 
  }
  post{
    always {
      echo "proceso finalizado"
    } 
}