library identifier: 'groovy@main', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/CarlosBarroso/groovy.git'])

pipeline {
    agent any
    stages {
        stage('Audit') {
            steps  {
                sh '''
        git version
        docker version
        dotnet --list-sdks
        dotnet --list-runtimes
      '''
            }
        }
    }
}
