//library identifier: 'groovy@main', 
//        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/CarlosBarroso/groovy.git'])

pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/dotnet/core/sdk:3.1.101'
        }
    }
    stages {
        stage('Audit') {
            steps  {
               jenkins-pipeline()
            }
        }
    }
}

void jenkins-pipeline() {   
      sh '''
        git version       
        dotnet --list-sdks
        dotnet --list-runtimes
      '''    
}
